### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by Greg-J** [Wondering-Oracle/BeholdersVariationsFabric#6]
A bunch of startup errors like the following:

```
May 13 04:42:41 afterdark1 java[13564]: [04:42:41] [Server thread/ERROR]: Couldn't parse loot table beholdersvariations:blocks/shadow_quartz_tiling_slab
May 13 04:42:41 afterdark1 java[13564]: java.lang.IllegalArgumentException: Can't find block beholdersvariations:shadow_quartz_tiling_slab
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_212$class_214.method_17937(class_212.java:79) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_292]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_212$class_214.method_910(class_212.java:79) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_212$class_214.method_517(class_212.java:68) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:83) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:887) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:952) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15283(class_3518.java:456) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_120$class_123.method_528(class_120.java:98) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_120$class_123.method_517(class_120.java:88) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:83) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:887) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:952) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15283(class_3518.java:456) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_85$class_90.method_441(class_85.java:149) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_85$class_90.method_424(class_85.java:129) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_79$class_5337.method_29319(class_79.java:86) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_79$class_5337.method_517(class_79.java:74) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_5330$class_5333.deserialize(class_5330.java:83) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:887) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:952) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15272(class_3518.java:448) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_55$class_57.method_358(class_55.java:169) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_55$class_57.deserialize(class_55.java:165) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:887) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:952) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15291(class_3518.java:440) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3518.method_15283(class_3518.java:456) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_52$class_54.method_340(class_52.java:213) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_52$class_54.deserialize(class_52.java:209) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:887) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:952) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.google.gson.Gson.fromJson(Gson.java:925) ~[server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_60.method_20711(class_60.java:44) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_292]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_60.method_20712(class_60.java:42) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_60.method_18788(class_60.java:17) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670) ~[?:1.8.0_292]
May 13 04:42:41 afterdark1 java[13564]:         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646) ~[?:1.8.0_292]
May 13 04:42:41 afterdark1 java[13564]:         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_292]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1344) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at com.sk89q.worldedit.fabric.FabricWorldEdit.onStartServer(FabricWorldEdit.java:221) ~[worldedit-mod-7.2.5-dist.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:48) ~[ec964abd-2c71-4861-95a2-ad68bd6f562d.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.handler$cnb000$afterSetupServer(MinecraftServer.java:11243) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
May 13 04:42:41 afterdark1 java[13564]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by Wondering-Oracle** [comment]
Thank you, it looks like I missed a block when removing shadow quartz.

**Comment by Wondering-Oracle** [comment]
New version has been uploaded to Curseforge, I'll wait until it's approved to close this issue.

**Comment by Wondering-Oracle** [comment]
File has been approved. Thank you for submitting this issue.
